name: pattle
description: An easy to use Matrix app.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  injector: ^1.0.6

  matrix_sdk: ^0.13.1
  matrix_sdk_sqflite: ^0.9.0

  rxdart: ^0.21.0

  # TODO: Use official package when PR is merged
  sentry:
    git: https://git.pattle.im/forks/sentry.git

  flutter_cache_manager: ^0.3.2

  device_info: ^0.4.0+1
  package_info: ^0.4.0+3

  # TODO (maybe): Use official package when PR is merged
  flutter_html:
    git: https://git.pattle.im/forks/flutter_html.git

  flutter_dotenv: ^2.0.1

  respect_24_hour: ^0.0.2

  transparent_image: ^1.0.0

  photo_view: ^0.3.1

  url_launcher: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.7.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"
  adaptive_icon_background: "#aa4139"
  adaptive_icon_foreground: "assets/icons/launcher-foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - .env
